name: Docker

on:
  push:
    branches: [ production ]

jobs:
    deploy:
        name: Deploy to Cloud Run

        runs-on: ubuntu-latest

        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}

        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Create .env file
          run: |
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
            echo BASIC_AUTH_USERNAME=${{ secrets.BASIC_AUTH_USERNAME }} >> .env
            echo BASIC_AUTH_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }} >> .env

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region ${{ secrets.GCP_REGION }} --allow-unauthenticated
